name: MoonAware
main: @mainClass@
version: @version@
author: Justin Lawen

depend: [HydraCore]

commands:
  MoonAware:
    description: Main command for MoonAware
    usage: /<command> reload
    permission: moonaware.command
    permissions message: You don't have <permission>
